const ADD_TODO = "ADD_TODO"
const REMOVE_TODO = "REMOVE_TODO"
const TOGGLE_TODO = "TOGGLE_TODO"
const CLEAR_COMPLETED_TODOS = "CLEAR_COMPLETED_TODOS"
const CHANGE_ACTIVE_FILTER = "CHANGE_ACTIVE_FILTER"

export {
  ADD_TODO,
  REMOVE_TODO,
  TOGGLE_TODO,
  CLEAR_COMPLETED_TODOS,
  CHANGE_ACTIVE_FILTER
}