const ADD_TODO_ITEM = "ADD_TODO_ITEM";
const REMOVE_TODO_ITEM = "REMOVE_TODO_ITEM";
const TOGGLE_TODO_ITEM = "TOGGLE_TODO_ITEM";
const CLEAR_COMPLETED_TODO_ITEMS = "CLEAR_COMPLETED_TODO_ITEMS";
const CHANGE_ACTIVE_FILTER = "CHANGE_ACTIVE_FILTER";
const SELECT_ALL_TODO_ITEMS = "SELECT_ALL_TODO_ITEMS";

export {
  ADD_TODO_ITEM,
  REMOVE_TODO_ITEM,
  TOGGLE_TODO_ITEM,
  CLEAR_COMPLETED_TODO_ITEMS,
  CHANGE_ACTIVE_FILTER,
  SELECT_ALL_TODO_ITEMS
}